apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ include "cve-manager.fullname" . }}-opengauss-cve-manager-tls
  labels:
  {{- include "cve-manager.labels" . | nindent 4 }}
spec:
  keysMap:
    ca.crt:
      key: server.crt
      path: secrets/data/infra-common/osinfra-cn
    tls.crt:
      key: server.crt
      path: secrets/data/infra-common/osinfra-cn
    tls.key:
      key: server.key
      path: secrets/data/infra-common/osinfra-cn
  name: opengauss-cve-manager-tls
