---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .Values.nameOverride }}-secrets
spec:
  name: {{ .Values.nameOverride }}-secrets
  keysMap:
    db-passwd:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: db-passwd
    db-uri:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: db-uri
    db-username:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: db-username
    aes-key:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: aes-key
    hook-pwd:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: hook-pwd
    gitee-token:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: gitee-token
    cve-email-sendaddr:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: cve-email-sendaddr
    cve-email-password:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: cve-email-password
    gitee_gauss_token:
      path: secrets/data/i{{ .Values.secret.path }}/cve-manager
      key: gitee_gauss_token
    gitee_mindspore_token:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: gitee_mindspore_token
    obs-key-id:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: obs-key-id
    obs-secret-key:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: obs-secret-key
    gitee-openlookeng-token:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: gitee-openlookeng-token
    upload_username:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: upload_username
    upload_password:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: upload_password
    gitee_majun_token:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: gitee_majun_token
    majun_api_id:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: majun_api_id
    majun_secret_key:
      path: secrets/data/{{ .Values.secret.path }}/cve-manager
      key: majun_secret_key


---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: {{ .Values.nameOverride }}-tls
  namespace: {{ .Values.namespace }}
spec:
  name: {{ .Values.nameOverride }}-tls
  keysMap:
    {{- with .Values.secretdefine.secret }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
